### ISSUE TITLE
Refactor computation

### ISSUE THREAD

**Issue by edolfo-stanford** [apoursh/HYDRA#9] opened 2018-12-14 20:57 UTC
Instead of having the computation (e.g. PCA, logistic regression, ...) written as functions within the networking component, create a separate module that contains each of the functions needed.  This also means refactoring the networking components to call the computation module accordingly.

**Comment by apoursh** [comment] 2019-10-04 21:11
This has been done but the issue is dangling so I will close it.

**Closed by apoursh** 2019-10-04 21:11 UTC
